class Config:    
    SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'XRP/USDT']
    TIMEFRAMES = ['1h', '1d']
    OHLCV_UPDATE_INTERVAL = 300
    ORDERBOOK_UPDATE_INTERVAL = 10
    OHLCV_LIMIT = 100 
    ORDERBOOK_LIMIT = 5
    STOP_LOSS_ATR = 1.5
    TAKE_PROFIT_ATR = 3.0
    SLIPPAGE = 0.0005
    FEE_RATE = 0.0004
    RISK_PER_TRADE = 0.005
    LEVERAGE = 10
    SYMBOL_PRECISION = 4
    CAPITAL = 1000000
    MAX_POSITIONS = 10
    MAX_RISK = 0.05
